[package]
name = "zero_pass_backend"
version = "0.0.6"
authors = ["caio <wabros@protonmail.com>"]
license = "GPL-3.0"
description = "The Zero Pass Project brain"
homepage = "https://github.com/CaioVieiraF/zero-pass-backend"
repository = "https://github.com/CaioVieiraF/zero-pass-backend"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
