[package]
name = "zero_pass_backend"
version = "0.0.1"
authors = ["caio <wabros@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
