[package]
name = "zero_pass_backend"
version = "0.2.1"
authors = ["caio <wabros@proton.me>"]
license = "GPL-3.0"
description = "The Zero Pass Project brain"
homepage = "https://gitlab.com/zero-pass/zero-pass-backend"
repository = "https://github.com/CaioVieiraF/zero-pass-backend"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.155", features=["derive"] }
serde_json = "1"
base64 = "0.21.0"
